### PR TITLE
Adds support to build and run nsfminer inside docker container

### PR DESCRIPTION
**Pull request by ikru**
Hi,

I've implemented nsfminer build/run process inside the container for my personal use. Would be happy to share with community.

I am adding two files:
dockerfile - which actually defines commands to build and run miner
.dockerignore - limits content which is getting copied inside the container

And there is also a readme file explaining how to run: 
docker-readme.md

I tested on my local ubuntu server:

Build works with both -DETHASHCUDA=ON -DETHASHCL=ON parameters. 
Run only tested on my nvidia GTX1080 card.

Please let me know if you have any questions or there is anything else I can do to make it useful for you.

Thanks

### CODE REVIEW

**Comment by jean-m-cyr** [comment]
I'd rather see this as a stand-alone github project that uses this repo as submodule. I could post a link to it in the README.

**Comment by jean-m-cyr** [comment]
On 2nd thought, this is useful! This doesn't break the native build, right? Also could you include builds with
-DETHASHCUDA=ON  -DETHASHCL=ON
-DETHASHCUDA=OFF  -DETHASHCL=ON

**Comment by ikru** [comment]
Hey Jean,

No it doesn't change native build, but it simplify configuration of the
environment for those familiar with docker.
Yes, sure, I'll add environment variables for both. Now it builds with both
ON.

**Comment by ikru** [comment]
Added build args for -DETHASHCUDA=ON -DETHASHCL=ON

**Comment by edurenye** [comment]
Thanks for adding this feature, works great for Nvidia.

If it has the option to turn OpenCL on I guess is because its supposed to work with it, right? What are the instructions to make it work with AMD Radeon graphic cards?

**Comment by ikru** [comment]
Thanks @edurenye for confirming it works for you for NVidia. 

As for OpenCL, you can build miner in OpenCL mode with docker build, but I couldn't try it with Radeon as I don't have a card. So if someone could try and add run container and instructions for OpenCL would be great.

**Pull request merged**
